server:
  port: 8090
  tomcat:
    max-threads: 2000
spring:
  profiles:
    active: dev
  security:
    basic:
      enabled: false
    user:
      name: fantacg
      password: fantacg!1314
  application:
    name: pay-service
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      maximum-pool-size: 150
      minimum-idle: 10
      connection-timeout: 60000
      read-only: false
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
  redis:
    host: sf.fantacg.com
    port: 6379
    password: fantacg@1314
    timeout: 60000
    jedis:
      pool:
        maxIdle: 500
        maxTotal: 2000
        maxWaitMillis: 2000
        minEvictableIdleTimeMillis: 300000
        numTestsPerEvictionRun: 1024
        timeBetweenEvictionRunsMillis: 30000
        testOnBorrow: true
        testWhileIdle: true
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: sf.fantacg.com
    port: 5672
    username: guest
    password: fantacg@1314
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  jackson:
    time-zone: GMT+8
# 注册中心服务于注册
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8079/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}  #指定实例id
  #分布式 雪花算法生成id
  worker:
    workerId: 1
    dataCenterId: 1
#阿里云图片身份证识别
aliyun:
  idcard:
    appcode: a1dd6e0872354ca6a45418ceda8fddb4  #阿里云图片身份证识别的套餐appcode
logging:
  level:
    com:
      fantacg: info
  config: classpath:config/logback-spring.xml