server:
  port: 8088
  tomcat:
    max-threads: 2000
spring:
  application:
    name: answer-service
  jackson:
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://sf.fantacg.com:3306/fantacg?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: fantacg@1314
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      default-auto-commit: true
      initial-size: 20
      max-active: 240
      max-wait: 10000
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1
      validation-query-timeout: 3
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 120000
      remove-abandoned: true
      remove-abandoned-timeout: 120
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      maximum-pool-size: 150
      minimum-idle: 10
      connection-timeout: 60000
      read-only: false
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
  redis:
    host: sf.fantacg.com
    port: 6379
    password: fantacg@1314
    timeout: 60000
    jedis:
      pool:
        maxIdle: 500 #最大空闲连接
        maxTotal: 2000
        maxWaitMillis: 2000
        minEvictableIdleTimeMillis: 300000
        numTestsPerEvictionRun: 1024
        timeBetweenEvictionRunsMillis: 30000
        testOnBorrow: true
        testWhileIdle: true
        min-idle: 100 #最小空闲连接
  rabbitmq:
    host: sf.fantacg.com
    port: 5672
    username: guest
    password: fantacg@1314
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
  security:
    basic:
      enabled: false
    user:
      name: fantacg
      password: fantacg!1314
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8079/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}  #指定实例id
mybatis:
  type-aliases-package: com.fantacg.answer.pojo
  mapper-locations: "classpath*:mybatis/*.xml"
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      fantacg: DEBUG
  config: classpath:config/logback-spring.xml
