server:
  port: 8083
  tomcat:
    max-threads: 2000
spring:
  profiles:
    active: dev
  security:
    basic:
      enabled: false
    user:
      name: fantacg
      password: fantacg!1314
  application:
    name: project-service
  datasource:
    url: jdbc:mysql://sf.fantacg.com:3306/fantacg?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: fantacg@1314
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      default-auto-commit: true
      initial-size: 20
      max-active: 240
      max-wait: 10000
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1
      validation-query-timeout: 3
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 120000
      remove-abandoned: true
      remove-abandoned-timeout: 120
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      maximum-pool-size: 150
      minimum-idle: 10
      connection-timeout: 60000
      read-only: false
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
  redis:
    host: sf.fantacg.com # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: fantacg@1314
    timeout: 60000 # redis连接超时时间（单位毫秒）
    jedis:
      pool:
        max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
  rabbitmq:
    host: sf.fantacg.com
    port: 5672
    username: guest
    password: fantacg@1314
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
      enabled: true
  jackson:
    time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8079/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
  #分布式 雪花算法生成id
  worker:
    workerId: 1
    dataCenterId: 1
mybatis:
  type-aliases-package: com.fantacg.common.pojo.project
  mapper-locations: "classpath*:mybatis/*.xml"
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      fantacg: DEBUG
  config: classpath:config/logback-spring.xml

