sf:
  jwt:
    pubkeypath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: SF_TOKEN # cookie的名称
  filter:
    allowPaths:   #不需要登录即可访问的路径
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code